debuggerd: Resolve tombstoned missing O_CREAT mode
 debuggerd/tombstoned/tombstoned.cpp:115:92:
  error: 'openat' has superfluous mode bits; missing O_CREAT?
    unique_fd result(openat(dir_fd_, ".",
    O_WRONLY | O_APPEND | O_TMPFILE | O_CLOEXEC, 0640));

Change-Id: Iae787e477b7eab1f11c79f30c35fd6808959e38a